version: "3.8"
services:
  web:
    build: ./api
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
      - /app/node_modules
    deploy:
      replicas: 3

  api:
    build: ./api
    ports:
      - "3001:3000"
    volumes:
      - ./api:/app
      - /app/node_modules
    deploy:
      replicas: 2
